when:
  event: manual

depends_on:
  - test

steps:
  - name: publish-pypi
    image: python:3.14
    environment:
      PYPI_TOKEN:
        from_secret: pypi_token
    commands:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.local/bin:$PATH"
      - git fetch --unshallow
      - ./scripts/ci/publish-pypi.sh
