when:
  event: [push, pull_request, manual]

matrix:
  python_version: ["3.11", "3.12", "3.13", "3.14"]

steps:
  - name: test
    image: python:${python_version}
    commands:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.local/bin:$PATH"
      - uv tool install prek
      - ./scripts/ci/test.sh
